[tool.pytest.ini_options]
addopts = "--disable-warnings --durations=5 --durations-min=0.1 -r a --strict-markers"
pythonpath = "src/"

[tool.ruff]
src = ["src"]

# list of rules and their explanations can be
# found at https://beta.ruff.rs/docs/rules/

select = [
  "F",    # pyflakes
  "E",    # pycodestyle
  "W",    # pycodestyle, warning
  "G",    # flake8-logging-format
  "COM",  # flake8-commas
  "YTT",  # flake8-2020
  "T10",  # flake8-debugger
  "ISC",  # flake8-implicit-str-concat
  "PIE",  # flake8-pie
  "PYI",  # flake8-pyi
  "Q",    # flake8-quotes
  "RSE",  # flake8-raise
  "SLOT", # flake8-slots
  "INT",  # flake8-gettext
  "ASYNC",  # flake8-async
  "C90",  # mccabe
  "I",    # isort
  "UP",   # pyupgrade
  "B",    # Bugbear
  "PGH",  # pygrep-hooks
  "PLE",  # Pylint - Error
  "PLW",  # Pylint - Warning
  "B",    # Bugbear
  "C4",   # flake8-comprehensions
  "RUF",  # Ruff-specific rules
]
ignore = ["E501", "PGH004", "B904", "G004", "COM812", "RUF012"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
# fixable = ["A", "B", "C", "D", "E", "F", "..."]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "vendor",
]
per-file-ignores = {}

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11.
target-version = "py311"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
